Data Preprocessing in DataFrame using Pandas and Scikit-Learn

In [ ]:
import pandas as pd

In [ ]:
# Sample DataFrame
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'John'],
    'Age': [24, 35, None, 28, 24],
    'Gender': ['M', 'F', 'M', 'F', 'M'],
    'Salary': [50000, 60000, 75000, None, 50000]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

    Name   Age Gender   Salary
0   John  24.0      M  50000.0
1   Anna  35.0      F  60000.0
2  Peter   NaN      M  75000.0
3  Linda  28.0      F      NaN
4   John  24.0      M  50000.0

In [ ]:
# Handling missing values
# Drop rows with any missing values
df.dropna(inplace=True)

In [ ]:
df

   Name   Age Gender   Salary
0  John  24.0      M  50000.0
1  Anna  35.0      F  60000.0
4  John  24.0      M  50000.0

In [ ]:
# Handling duplicates
df.drop_duplicates(inplace=True)

In [ ]:
df

   Name   Age Gender   Salary
0  John  24.0      M  50000.0
1  Anna  35.0      F  60000.0

In [ ]:
# Encoding categorical variables
# Convert Gender to numerical using one-hot encoding
df = pd.get_dummies(df, columns=['Gender'], drop_first=True)

In [ ]:
df

   Name   Age   Salary  Gender_M
0  John  24.0  50000.0         1
1  Anna  35.0  60000.0         0

In [ ]:
# Scaling numerical features (e.g., using Min-Max scaling)
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])

In [ ]:
# Display the preprocessed DataFrame
print("Preprocessed DataFrame:")
print(df)

Preprocessed DataFrame:
   Name  Age  Salary  Gender_M
0  John  0.0     0.0         1
1  Anna  1.0     1.0         0